# Generated by Django 4.1.2 on 2022-10-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myterms', '0002_boosting_coach_sell_account_sell_games_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boosting',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='coach',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
