# Generated by Django 4.1.2 on 2022-10-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myterms', '0003_boosting_photo_coach_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='boosting',
            name='post_type',
            field=models.CharField(choices=[('Boosting', 'Boosting')], default='Boosting', max_length=14),
        ),
        migrations.AddField(
            model_name='coach',
            name='post_type',
            field=models.CharField(choices=[('Coach', 'Coach')], default='Coach', max_length=14),
        ),
        migrations.AddField(
            model_name='sell_account',
            name='post_type',
            field=models.CharField(choices=[('Sprzedaż Konta', 'Sprzedaż Konta')], default='Sprzedaż Konta', max_length=14),
        ),
        migrations.AddField(
            model_name='sell_games',
            name='post_type',
            field=models.CharField(choices=[('Sprzedaż Gry', 'Sprzedaż Gry')], default='Sprzedaż Gry', max_length=14),
        ),
    ]
